# Singular Value Decomposition (toy example) with PyTorch
- Factorization of arbitrary rectangular matrix to attain singular vector containing the data geometry and distribution of the corresponding matrix
- M = U S V^T 

In [1]:
import torch

z = torch.rand(4, 6)
z

tensor([[0.7595, 0.5575, 0.4986, 0.6303, 0.6394, 0.2365],
        [0.7128, 0.0491, 0.0623, 0.0117, 0.4364, 0.8856],
        [0.8374, 0.2359, 0.9320, 0.8358, 0.2228, 0.1026],
        [0.2931, 0.4414, 0.7421, 0.5517, 0.7170, 0.1612]])

In [2]:
z.shape

torch.Size([4, 6])

In [3]:
U, S, V = torch.svd(z) # SVD

In [4]:
U # dim: 4*4

tensor([[-0.5610,  0.0225, -0.2454,  0.7903],
        [-0.3212,  0.9144,  0.1133, -0.2189],
        [-0.5858, -0.3383,  0.7129, -0.1848],
        [-0.4889, -0.2213, -0.6471, -0.5416]])

In [5]:
S # singular vector we are looking for 

tensor([2.4705, 1.0087, 0.5791, 0.3021])

In [8]:
V # dim: 6*4

tensor([[-0.5217,  0.3179,  0.5211,  0.4329],
        [-0.2762, -0.1190, -0.4294,  0.4872],
        [-0.4891, -0.4078,  0.1191, -0.6410],
        [-0.4520, -0.3767,  0.1478,  0.1402],
        [-0.3966,  0.1779, -0.7125, -0.0652],
        [-0.2251,  0.7382,  0.0192, -0.3747]])

In [9]:
diagonal = torch.diag(S) # convert the singular vector back to the middle diagonal matrix
print(diagonal) # dim: 4*4

tensor([[2.4705, 0.0000, 0.0000, 0.0000],
        [0.0000, 1.0087, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.5791, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.3021]])


we can multiply the three matrices back (U S V^T) to verify if we can get the original matrix back

In [10]:
torch.mm(torch.mm(U, diagonal), V.t()) 

tensor([[0.7595, 0.5575, 0.4986, 0.6303, 0.6394, 0.2365],
        [0.7128, 0.0491, 0.0623, 0.0117, 0.4364, 0.8856],
        [0.8374, 0.2359, 0.9320, 0.8358, 0.2228, 0.1026],
        [0.2931, 0.4414, 0.7421, 0.5517, 0.7170, 0.1612]])

This is how we can attain the singular vector of matrices (which is about the data geometric distribution we will further use)